name: hakim
description: "Hakim healthcare access application for the Gaza Strip."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  firebase_core: ^4.14.0

  # عرض Google Map داخل التطبيق
  google_maps_flutter: ^2.18.0

  # الحصول على موقع الجهاز الحالي
  geolocator: ^14.0.3

  # تحويل الإحداثيات إلى عنوان مقروء
  geocoding: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ThmanyahSerifDisplay
      fonts:
        - asset: assets/fonts/thmanyahserifdisplay-Light.otf
          weight: 300
        - asset: assets/fonts/thmanyahserifdisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/thmanyahserifdisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/thmanyahserifdisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/thmanyahserifdisplay-Black.otf
          weight: 900