// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwLfSK_uD3BdcxiydgIJG_LjH432-wGFE',
    appId: '1:288536802728:web:f7cc7139eb0d51149f999d',
    messagingSenderId: '288536802728',
    projectId: 'hakim-5a7b2',
    authDomain: 'hakim-5a7b2.firebaseapp.com',
    storageBucket: 'hakim-5a7b2.firebasestorage.app',
    measurementId: 'G-XFGDB0J1MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFCBEOoMxAuN24_2IQbnxTsQjVyZIS6EE',
    appId: '1:288536802728:android:caf6fc802253074f9f999d',
    messagingSenderId: '288536802728',
    projectId: 'hakim-5a7b2',
    storageBucket: 'hakim-5a7b2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaMhSRe-H1BKu0aMYGHe8hnQwhmuri98',
    appId: '1:288536802728:ios:c2a82206fd7ffdf29f999d',
    messagingSenderId: '288536802728',
    projectId: 'hakim-5a7b2',
    storageBucket: 'hakim-5a7b2.firebasestorage.app',
    iosBundleId: 'com.example.hakim',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMaMhSRe-H1BKu0aMYGHe8hnQwhmuri98',
    appId: '1:288536802728:ios:c2a82206fd7ffdf29f999d',
    messagingSenderId: '288536802728',
    projectId: 'hakim-5a7b2',
    storageBucket: 'hakim-5a7b2.firebasestorage.app',
    iosBundleId: 'com.example.hakim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwLfSK_uD3BdcxiydgIJG_LjH432-wGFE',
    appId: '1:288536802728:web:215688497bc5e5f09f999d',
    messagingSenderId: '288536802728',
    projectId: 'hakim-5a7b2',
    authDomain: 'hakim-5a7b2.firebaseapp.com',
    storageBucket: 'hakim-5a7b2.firebasestorage.app',
    measurementId: 'G-Q8HRY739MB',
  );
}
